{"name": "Принятие заказа с id курьера и id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: Код ответа 409 и текст ответа {\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}\nassert 409 == 201\n +  where 409 = <Response [409]>.status_code", "trace": "@pytest.fixture\n    def create_login_and_delete_new_courier():\n        # задаём необходимые параметры нгового курьера\n        login = DataCourier.LOGIN\n        password = DataCourier.PASSWORD\n        first_name = DataCourier.FIRST_NAME\n    \n        # создаем нового курьера\n        create = CreateNewCourier().create_new_courier(login=login, password=password, first_name=first_name)\n>       assert create.status_code == 201, f'Код ответа {create.status_code} и текст ответа {create.text}'\nE       AssertionError: Код ответа 409 и текст ответа {\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}\nE       assert 409 == 201\nE        +  where 409 = <Response [409]>.status_code\n\nconftest.py:17: AssertionError"}, "description": "Принятие заказа с передачей id курьера и id заказа в запросe", "start": 1712531633073, "stop": 1712531633073, "uuid": "a418910d-3361-4386-93f7-0a8997975381", "historyId": "d388acaa9fc3d65d7a6596e99c362110", "testCaseId": "d388acaa9fc3d65d7a6596e99c362110", "fullName": "tests.test_order.test_accept_order.TestAcceptOrder#test_accept_order", "labels": [{"name": "parentSuite", "value": "tests.test_order"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "WIN-081B0PRJBJT"}, {"name": "thread", "value": "828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order.test_accept_order"}]}